#!/bin/bash

source "${ENTANDO_COMMON_PATH}/translate-jboss-variables.sh"
unset ENV_FILES #because we already have their values in the environment. The EAP image doesn't merge ENV_FILES with the environment, but creates duplicate datasources

LOCATION_CMS_CONTENT="<location name=\"${RESOURCEROOTURL}\" handler=\"cmscontent\"/>"
if [ "$CDS_ENABLED" == "true" ]; then
  LOCATION_CMS_CONTENT=""
fi
sed  -i 's@##LOCATION_CMS_CONTENT##@'"$LOCATION_CMS_CONTENT"'@' /opt/eap/standalone/configuration/standalone-openshift.xml

"${ENTANDO_COMMON_PATH}/prepare-data.sh"

if [ "$ENTANDO_WEB_CONTEXT" == "/" ]; then
  MYCONTEXT="ROOT"
else
  MYCONTEXT="$ENTANDO_WEB_CONTEXT"
fi

if [ "$REDIS_SESSION_ACTIVE" == "true" ]; then
  echo "REDIS_SESSION_ACTIVE env var is $REDIS_SESSION_ACTIVE on eap reset to false"
  export REDIS_SESSION_ACTIVE="false"
fi

mv /deployments/entando-de-app.war "/deployments/$MYCONTEXT.war"
exec "$JBOSS_HOME/bin/openshift-launch.sh"
