#!/bin/bash

source "${ENTANDO_COMMON_PATH}/translate-jboss-variables.sh"
unset ENV_FILES #because we already have their values in the environment. The EAP image doesn't merge ENV_FILES with the environment, but creates duplicate datasources
sed  -i 's@##RESOURCEROOTURL##@'"$RESOURCEROOTURL"'@' /opt/eap/standalone/configuration/standalone-openshift.xml
"${ENTANDO_COMMON_PATH}/prepare-data.sh"

if [ "$ENTANDO_WEB_CONTEXT" == "/" ]; then
  MYCONTEXT="ROOT"
else
  MYCONTEXT="$ENTANDO_WEB_CONTEXT"
fi

mv /deployments/entando-de-app.war "/deployments/$MYCONTEXT.war"
exec "$JBOSS_HOME/bin/openshift-launch.sh"
