#!/bin/bash

source "${ENTANDO_COMMON_PATH}/translate-jboss-variables.sh"
"${ENTANDO_COMMON_PATH}/prepare-data.sh"

LOCATION_CMS_CONTENT="<location name=\"${RESOURCEROOTURL}\" handler=\"cmscontent\"/>"
if [ "$CDS_ENABLED" == "true" ]; then
  LOCATION_CMS_CONTENT=""
fi
sed  -i 's@##LOCATION_CMS_CONTENT##@'"$LOCATION_CMS_CONTENT"'@' /wildfly/standalone/configuration/standalone.xml

if [ "$ENTANDO_WEB_CONTEXT" == "/" ]; then
  MYCONTEXT="ROOT"
else
  MYCONTEXT="$ENTANDO_WEB_CONTEXT"
fi

if [ "$REDIS_SESSION_ACTIVE" == "true" ]; then
  echo "REDIS_SESSION_ACTIVE env var is $REDIS_SESSION_ACTIVE on wildfly reset to false"
  export REDIS_SESSION_ACTIVE="false"
fi

mv /wildfly/standalone/deployments/entando-de-app.war "/wildfly/standalone/deployments/$MYCONTEXT.war"
exec "$JBOSS_HOME/bin/openshift-launch.sh"
