#!/bin/bash

source "${ENTANDO_COMMON_PATH}/translate-jboss-variables.sh"
"${ENTANDO_COMMON_PATH}/prepare-data.sh"
sed  -i 's@##RESOURCEROOTURL##@'"$RESOURCEROOTURL"'@' /wildfly/standalone/configuration/standalone.xml

if [ "$ENTANDO_WEB_CONTEXT" == "/" ]; then
  MYCONTEXT="ROOT"
else
  MYCONTEXT="$ENTANDO_WEB_CONTEXT"
fi

mv /wildfly/standalone/deployments/entando-de-app.war "/wildfly/standalone/deployments/$MYCONTEXT.war"
exec "$JBOSS_HOME/bin/openshift-launch.sh"
